/* Mail Karo — FINAL PUBLIC URL PDF ENGINE */
(function () {
  function ready(fn) {
    if (document.readyState !== "loading") fn();
    else document.addEventListener("DOMContentLoaded", fn);
  }

  ready(() => {
    const outEl = document.getElementById("outputText");
    const downloadBtn = document.getElementById("mkPdfDownloadBtn");
    const previewBtn = document.getElementById("mkPdfPreviewBtn");

    if (!outEl || !downloadBtn || !previewBtn) {
      console.warn("PDF section elements missing");
      return;
    }

    /* ----------------------------------------------------------
       1) BUTTON STATE CONTROL
    ---------------------------------------------------------- */
    function disableBtns() {
      downloadBtn.disabled = true;
      previewBtn.disabled = true;
      downloadBtn.style.opacity = "0.5";
      previewBtn.style.opacity = "0.5";
      downloadBtn.style.cursor = "not-allowed";
      previewBtn.style.cursor = "not-allowed";
    }

    function enableBtns() {
      downloadBtn.disabled = false;
      previewBtn.disabled = false;
      downloadBtn.style.opacity = "1";
      previewBtn.style.opacity = "1";
      downloadBtn.style.cursor = "pointer";
      previewBtn.style.cursor = "pointer";
    }

    disableBtns(); // start disabled


    /* ----------------------------------------------------------
       2) LIVE DETECTION — ENABLE BUTTONS WHEN EMAIL READY
    ---------------------------------------------------------- */
    const observer = new MutationObserver(() => {
      const t = outEl.innerText.trim();

      if (
        !t ||
        t.includes("Your AI-generated email will appear here") ||
        t.includes("Generating email") ||
        t.length < 10
      ) {
        disableBtns();
      } else {
        enableBtns();
      }
    });

    observer.observe(outEl, { childList: true, subtree: true });


    /* ----------------------------------------------------------
       3) LOAD jsPDF
    ---------------------------------------------------------- */
    function loadJsPDF() {
      return new Promise((resolve, reject) => {
        if (window.jspdf) return resolve(window.jspdf.jsPDF);

        const s = document.createElement("script");
        s.src =
          "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";
        s.onload = () => resolve(window.jspdf.jsPDF);
        s.onerror = () => reject("Failed to load jsPDF");
        document.head.appendChild(s);
      });
    }


    /* ----------------------------------------------------------
       4) PUBLIC URL WATERMARK (SAFE)
    ---------------------------------------------------------- */
    const watermarkURL =
      "https://mail-karo.netlify.app/All%20Images/Logo.png";

    function loadWatermark() {
      return fetch(watermarkURL)
        .then((r) => r.blob())
        .then(
          (blob) =>
            new Promise((resolve) => {
              const reader = new FileReader();
              reader.onload = () => resolve(reader.result);
              reader.readAsDataURL(blob);
            })
        )
        .catch(() => null);
    }


    /* ----------------------------------------------------------
       5) PDF CREATOR
    ---------------------------------------------------------- */
    async function createPdf({ preview = false }) {
      const text = outEl.innerText.trim();
      if (!text || text.includes("Generating")) {
        alert("Generate an email first.");
        return;
      }

      const jsPDF = await loadJsPDF();
      const doc = new jsPDF({ unit: "pt", format: "a4" });

      const pageW = doc.internal.pageSize.getWidth();
      const pageH = doc.internal.pageSize.getHeight();
      const margin = 40;

      /* Body text */
      const body = doc.splitTextToSize(text, pageW - margin * 2);
      let y = 40;

      doc.setFontSize(12);
      doc.setTextColor(40, 40, 40);

      body.forEach((line) => {
        if (y > pageH - 60) {
          doc.addPage();
          y = 40;
        }
        doc.text(line, margin, y);
        y += 16;
      });

      /* Watermark */
      const watermark = await loadWatermark();
      if (watermark) {
        const pages = doc.getNumberOfPages();

        for (let p = 1; p <= pages; p++) {
          doc.setPage(p);
          doc.addImage(
            watermark,
            "PNG",
            (pageW - 260) / 2,
            (pageH - 260) / 2,
            260,
            260,
            "",
            "NONE",
            0.15 // opacity
          );
        }
      }

      /* Footer */
      doc.setFontSize(10);
      doc.setTextColor(160, 140, 40);
      doc.text("Generated by Mail Karo", margin, pageH - 30);

      /* Save or Preview */
      if (preview) {
        window.open(doc.output("bloburl"), "_blank");
      } else {
        doc.save("MailKaro_Email.pdf");
      }
    }

    /* ----------------------------------------------------------
       6) BUTTON EVENTS
    ---------------------------------------------------------- */
    downloadBtn.onclick = () => createPdf({ preview: false });
    previewBtn.onclick = () => createPdf({ preview: true });
  });
})();
